### ISSUE TITLE
Can't build the project

### ISSUE THREAD

**Issue by MichaelBac** [goldbattle/copernicus#2]
Hi,

I install MSYS2 x86_64 from https://msys2.github.io/ and add the new variables to PATH.
if i run make i got this error:

```
g++ -g -std=c++11 -Iincludes -Llibs -D_GLIBCXX_USE_CXX11_ABI=0 -o copernicus.exe src/main.cpp src/copernicus/Copernicus.cpp src/copernicus/MyNetwork.cpp src/happyhttp/happyhttp.cpp -lws2_32
process_begin: CreateProcess(NULL, g++ -g -std=c++11 -Iincludes -Llibs -D_GLIBCXX_USE_CXX11_ABI=0 -o copernicus.exe src/main.cpp src/copernicus/Copernicus.cpp src/copernicus/MyNetwork.cpp src/happyhttp/happyhttp.cpp -lws2_32, ...) failed.
make (e=2): The system cannot find the file specified.
Make: *** [all] Error 2
```

i run this on 32-Bit Win7 and the new PATH-Variables are C:\msys32\mingw32\bin and C:\msys32\usr\bin

**Comment by goldbattle** [comment]
Seems that msys2 isn't install correctly, and doesn't have access to all the libraries.
Did you do the install instructions on the website?

* Run MSYS2 Shell
* `pacman -Syu`
* Restart
* `pacman -Su`

If not, I am not sure what is causing this to fail.

**Comment by MichaelBac** [comment]
I download the 32 Bit Version of MSYS2 and install it.

- `pacman -Syu`

` There is nothing to do`

- `pacman -Su`

` There is nothing to do`

I add the PATH-Variables to:
`right click on Computer -> Properties -> Advanced system settings -> Environment Variables ->System Variables -> PATH`
and reboot the PC.
Then I open `cmd` and go to:
`C:\copernicus-master\source\` 
and run make...

same error

Edit:

is this program able to start on 32Bit Systems?

**Comment by goldbattle** [comment]
I am not sure if it is possible to run on 32 bit machines, I only have 64bit machines so I have been unable to test that. Are you able to run the compiler from the command line?
```cmd
> g++
g++: fatal error: no input files
compilation terminated.
```

**Comment by MichaelBac** [comment]
no.

`the command g ++ is written either incorrect or could not be found`

`c:\msys32\mingw32\bin` and `c:\msys32\mingw64\bin` are empty.

This helps me to install the missing compiler:
https://github.com/orlp/dev-on-windows/wiki/Installing-GCC--&-MSYS2

thx for your help
