### ISSUE TITLE
what does add to path mean

### ISSUE THREAD

**Issue by nadeemohd** [goldbattle/copernicus#3]
Add C:\msys64\mingw64\bin and C:\msys64\usr\bin to PATH
what does it mean and how to add to the path i did not understand

**Comment by goldbattle** [comment]
Your windows path variable.
This allows for your command prompt (cmd.exe) to use the executable files in those directories.
https://superuser.com/questions/949560/how-do-i-set-system-environment-variables-in-windows-10
